language: go

before_install:
   - sudo add-apt-repository -y ppa:costamagnagianfranco/locutusofborg-ppa
   - sudo apt-get update -qq
   - sudo apt-get install libclang-dev -qq

install: 
   - git checkout release/clang-3.0
   - go get -d -v ./...
   - go build -v ./...

script: go test ./...

notifications:
  email:
    recipients:
      - binet@cern.ch
    on_success: change
    on_failure: always
